# Ubuntu environment (18.04)
dist: xenial

# C
language: c

# Compiler
compiler:
  - gcc

# Script to execute
script:
  # Change directory
  - cd src/
  # Compile
  - gcc -fprofile-arcs -ftest-coverage -O3 -Wall zps.c -o zps
  # Run
  - ./zps
  # Print code coverage information
  - gcov zps.c

# Only clone the most recent commit
git:
  depth: 1