# Ubuntu environment (18.04)
dist: xenial
# C
language: c
# Compiler
compiler:
  - gcc
# Disable sudo for faster build
sudo: false
# Script to execute
script:
  # Compile the example & run
  - cd example
  - gcc -O3 -Wall zproc.c -o z\ \proc.o
  - seq 5 | xargs -I -- ./z\ proc.o &>/dev/null &
  # Compile the main source & run
  - cd ../src/
  - gcc -fprofile-arcs -ftest-coverage -O3 -Wall zps.c -o zps
  - ./zps -v && ./zps -h && printf '1,2' | ./zps -p
  - ./zps -x && ./zps -lr && ./zps -f
  - ./zps -r -f 20 && ./zps -s
  # Print code coverage information
  - gcov zps.c
# Send report to codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
# Only clone the most recent commit
git:
  depth: 1